filebeat.prospectors:
    - type: log
      enabled: true
      tags:
        - tweetapp_1_nginx
      paths:
        - /usr/share/services/nginx/*.log
    - type: log
      enabled: true
      tags:
        - tweetapp_1_pm2
      paths:
        - /usr/share/services/node/*.log

output.kafka:
  hosts: ["kafka:9092"]
  topic: 'TweetAppTopic'
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000